# Generated by Django 3.2.6 on 2022-05-25 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'closed'), (2, 'reversed'), (3, 'pending')], verbose_name='status')),
                ('approved_status', models.BooleanField(verbose_name='approved status')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['timestamp'],
            },
        ),
    ]
