# Generated by Django 3.2.6 on 2022-05-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='approved_status',
            new_name='status_approved',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='status',
            new_name='status_transaction',
        ),
    ]
